---
title: "Codebook For Case Study 1"
author: "Allen Ansari,Audrene Tiakor"
date: "March 2, 2019"
output: html_document
---
#### github link: https://github.com/allenansari174/Beer_Study

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Backstory
The CEO and CFO of Budweiser (my client) has given me as a Data Scientist two separate data sets with the intent of reporting any interesting findings uncovered after strategically applying certain tools and concepts to these datasets. The strategic tools and concepts that will be used in application is tidying the data (merging the two datasets and making the data ready for analysis), finding the number of breweries in each state, computing the median alcohol content (ABV) and international betterness of each state (IBU), finding which state has the the maximum alcohol content and which state has the most bitter beer. After these analyses, the question 'Is there an apparent relationship between the bitterness of the beer and its alcoholic content?' will be answered to ignite a further analysis into what interesting things that this data has for us to uncover. 

###Libraries used:
``````````
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(dplyr) # Heavy use of this library
library(tidyr)
library(plyr)
library(ggthemes) # for themes in ggplot
library(knitr)
library(kableExtra) # library to make the document more presentable
``````````
#Raw Data
The raw data for this task consists of the following data sets:

**Beers.csv** This file contains a list of 2410 US craft Beers. The data descriptions are as follows:
- Name: Name of the beer.
- Beer_ID: Unique identifier of the beer.
- ABV: Alcohol by volume of the beer.
- IBU: International Bitterness Units of the beer. 
- Brewery_ID: Brewery id associated with the beer.
- Style: Style of the beer.
- Ounces: Ounces of beer. 

**Breweries.csv** This file contains 558 US breweries. The data descriptions are as follows: 
- Brew_ID: Unique identifier of the brewery.
- Name: Name of the brewery.
- City: City where the brewery is located.
- State: U.S. State where the brewery is located.

#Variables created with Explaination:
* **Beers** - variable created for raw data 'Beers.csv'
* **Breweries** - variable created for raw data 'Breweries.csv'
* **BrewPerState** - variable created to show the number of breweries in each state
* **BrewPub** - variable created for the merge of Beers and Breweries data sets
* **Alc** - variable for function created to compute the median alcohol content unit for each state
* **Bitter** - variable created to compute the median international bitterness unit for each state
* **Max_ABV** - variable created to find the state which has has the maximum alcoholic (ABV) beer
* **Max_IBU**- variable created to find state which has has the maximum alcoholic (IBU) beer
* **StateAbb**- variable used to denote the creation of the region column
* **StateRegion**- variable used to name the dataframe State.region
* **State**- variable used to show the step of combinding the region column to the original dataset 'BrewPub' by the State column
* **BrewRegion**- variable created for the final merge of the column region to the original dataset
* **ABV_Hist**- variable for the histogram of the alcohol by volume of beer by region
* **IBU_Hist**- variable for the histogram of the international bitterness units of beer by region
* **IBU_Box**- variable for the boxplot of the international bitterness units of beer by region
* **ABV_Box**- variable created to find state which has has the maximum alcoholic (IBU) beer by region
* **BeerABV.aov**- variable for the Analysis of Variance for the ABV mean by region
* **BeerIBU.aov**- variable for the Analysis of Variance for the IBU mean by region


##Tidy Data (Steps for how to go from raw to tidy data to serve question of interest)

#### Import/ merge data sets 'Beers' and 'Breweries':

``````````
# import Beers and Breweries files
Beers <- read_csv('Beers.csv', col_types = cols())
Breweries <- read_csv('Breweries.csv', col_types = cols())

# Merge Beers and Breweries files
BrewPub <- merge(Beers, Breweries, by.x = "Brewery_id", by.y = "Brew_ID", all = TRUE)

# Change variable names to more meaningful title
BrewPub <- rename(BrewPub, c("Name.x"="Beer","Name.y"="Brewery",
                   "Ounces"="OZ"))

# Used kable library to make document more presentable
kable(BrewPub %>% 
         head()) %>%
         kable_styling("striped", full_width = F)
        

kable(BrewPub %>% 
         tail()) %>%
         kable_styling("striped", full_width = F) 



``````````
#### Report the number of NA's in each column
````````
MissingValues <- sapply(BrewPub, function(MissingValue)sum(is.na(MissingValue)))

# Used kable library to make document more presentable
as.data.frame(MissingValues) %>%
  kable("html") %>%
  kable_styling("striped", full_width = F) 
````````
#### Creating a Region Column to look at ABV and IBU by Region

````````
# Creating Region Col
StateAbb <- as.data.frame(state.abb) # usnig stat.abb dataset 
StateRegion <- as.data.frame(state.region) # using state.region dataset
# Combine 2 datasets
State <- cbind(StateAbb,StateRegion)
names(State) <- c("State" , "Region")
# Merge State by BrewPub
BrewRegion <- merge(BrewPub,State, by="State")
````````
####Replacing missing values in IBU and ABV column with their respective means
````````
# Replacing IBU Missing Value by Region mean
BrewRegion[is.na(BrewRegion$IBU), "IBU"] <- tapply(BrewRegion$IBU, BrewRegion$Region, mean,na.rm=TRUE)[ BrewRegion[is.na(BrewRegion$IBU),"Region"]] 

# Replacing ABV Missing Value by Region mean
BrewRegion[is.na(BrewRegion$ABV), "ABV"] <- tapply(BrewRegion$ABV, BrewRegion$Region, mean,na.rm=TRUE)[ BrewRegion[is.na(BrewRegion$ABV),"Region"]]

# Missing Map after replacing NAs by mean

missmap(BrewRegion,y.at=c(1),y.labels = c(''),col=c('yellow','black'))
````````
##Analyzing The Data (By State):
Since, we are focusing on the alcohol content and the international bitterness for each state, we would like to use EDA to look at the missing values, the  median IBU and ACV by state, the maximum IBU and ABV by state, and use a scatter plot to see if there is an apparent relations ship between ABV and IBU.

#### Compute the Median of the alcohol content (ABV) and International Bitterness Unit (IBU) with respective plots
``````````
# Median of alcohol content
Alc <- BrewPub %>%
  na.omit()  %>%
group_by(State) %>%
summarise_each(funs(median), Median_ABV = ABV) %>%
arrange(Median_ABV)
Alc

#Plot of Median ABV by State

ggplot(data=Alc, aes(x=State, y=sort(Median_ABV,decreasing = TRUE))) +
  geom_bar(stat="identity", fill="red")+
  theme_bw() + 
  scale_color_economist()+
  theme(axis.text.x=element_text(size=rel(0.8), angle=90),plot.title = element_text(size=14,hjust = 0.5, face="bold.italic")) +
  ggtitle("Median ABV by State") +
  labs(x="State",y="ABV")

#Median of international bitterness unit

Bitter <- BrewPub %>%
  na.omit() %>%
group_by(State) %>%
summarise_each(funs(median), Median_IBU = IBU) %>%
arrange(Median_IBU)
Bitter

#Plot of Median IBU by State

ggplot(data=Bitter, aes(x=State, y=Median_IBU)) +
  geom_bar(stat="identity", fill="steelblue")+
  theme_bw() + 
  scale_color_economist()+
  theme(axis.text.x=element_text(size=7, angle=90),plot.title = element_text(size=14,hjust = 0.5, face="bold.italic"))+ ggtitle("Median IBU by State") + labs(x="State",y="IBU")
``````````
####Find Which state has the Most ABV and IBU
````````
#maximum ABV by state

Max_ABV <- Alc[which.max(Alc$Median_ABV),]
Max_ABV

#maximum IBU by state
Max_IBU <- Bitter[which.max(Bitter$Median_IBU),]
Max_IBU

````````
####Find the summary statitistics for both ABV and IBU
````````
#summary statitics for Alcohol Content
summary(BrewPub$ABV)

#summary statistics for International Bitterness Unit
summary(BrewPub$IBU)

````````
####Plot Scatter plot to see if there is an apparent relationship between IBU and ACV
``````````
ggplot(BrewPub, aes(x=BrewPub$IBU, y=BrewPub$ABV)) + geom_point() + geom_smooth(method=lm, se=FALSE) + theme(plot.title = element_text(size=14,hjust= 0.5, face="bold.italic")) + ggtitle("Relationship Between Bitterness of Beer and Its Alcoholic Content") +
  labs(x="Bitterness",y="Alcoholic Content") 

``````````
### Regression Line for relationship between IBU and ABV

````````
# Compute ANOVA for ABV and IBU
reg1 <- lm(ABV ~ IBU, data = BrewPub)
# Summary of reg 1
summary(reg1)

# Create a function to pull the data out of a linear regression, return values such as  (R-squares, slope, intercept and P value) at the top of a nice ggplot graph with the regression line.
Regressionplot <- function (reg) {
 
require(ggplot2)

 ggplot(reg$model, aes_string(x = names(reg$model)[2], y = names(reg$model)[1])) + geom_point() + stat_smooth(method = "lm", col = "red") + labs(title = paste("Adj R2 = ",signif(summary(reg)$adj.r.squared, 5), "Intercept =",signif(reg$coef[[1]],5 ), " Slope =",signif(reg$coef[[2]], 5), " P =",signif(summary(reg)$coef[2,4], 5)))
 }

# Compute reg1
reg1 <- lm(ABV ~ IBU, data = BrewPub)
# Summary of reg 1
summary(reg1)
#Final regression plot with R^2 adj, intercept/slope of linear regression line, and p-value
Regressionplot(reg1)

````````
There is strong evidence that our regression model is statistically signicficant with a p-value of 3.2634e^(-184). In other words, the coefficients of our model are not equal to zero, which is an indication that there exist a relationship between International Bitterness Unit and Alcohol by volume of the beer. This relationship can be modeled by the following linear regression equation: ABV = 0.04493 + 0.000350(IBU). This equation can be used to predict ABV, when we only have IBU for information. Also, notice that the adjusted R^2, is 0.44934. This value tells us that 44.93% of variation in ABV is explained by this model (the linear relationship between IBU and ABV).

## Further Analysis of The Data (By Region):
After using the visual evidence of the scatter plot of the relationship between IBU and ACV, further analysis was used to look at the IBU and ACV of regions. The states were taken and split into the following regions: South, West, Northeast, and North Central . After each state was separated into their respective regions, Explanatory Data Analysis and ANOVA was used to see if there was any significant results between IBU and ACV of each region.
````````
# Histogram of ABV
ABV_Hist <- ggplot(BrewRegion,aes(x=ABV)) + geom_histogram(aes(fill=Region)) +theme(axis.text.x=element_text(size=7), plot.title = element_text(size=14,hjust = 0.5, face="bold.italic"))+ ggtitle("Histogram of Alcohol Content By Region") + labs(x="ABV",y="Count")
ABV_Hist

# Histogram of IBU
ABV_Hist <- ggplot(BrewRegion,aes(x=IBU)) + geom_histogram(aes(fill=Region)) +theme(axis.text.x=element_text(size=7), plot.title = element_text(size=14,hjust = 0.5, face="bold.italic"))+ ggtitle("Histogram of Beer Bitterness By Region") + labs(x="IBU",y="Count")
ABV_Hist

# Boxplot of Alcohol Content By Region
Alch<-ggplot((BrewRegion), aes(x = Region, y = ABV)) + geom_boxplot() + theme(axis.text.x=element_text(size=7, angle=90), plot.title = element_text(size=14,hjust = 0.5, face="bold.italic"))+ ggtitle("Boxplot of Alcohol Content By Region") + labs(x="Region",y="ABV")
Alch

# Boxplot of Beer Bitterness By Region
Bitt<- ggplot((BrewRegion), aes(x = Region, y = IBU)) + geom_boxplot() + theme(axis.text.x=element_text(size=7, angle=90), plot.title = element_text(size=14,hjust = 0.5, face="bold.italic"))+ ggtitle("Boxplot of Beer Bitterness By Region") + labs(x="Region",y="IBU")
Bitt

# ABV per Region Bar Plot
ggplot(BrewRegion, aes(x=Region, y=ABV)) +
  geom_bar(stat="identity", fill="red")+
  theme_bw() + 
  scale_color_economist()+
  theme(axis.text.x=element_text(size=rel(0.8), angle=90),plot.title = element_text(size=14,hjust = 0.5, face="bold.italic")) +
  ggtitle("Median ABV by Region") +
  labs(x="Region",y="ABV")

# IBU per Region Bar plot
ggplot(BrewRegion, aes(x=Region, y=IBU)) +
  geom_bar(stat="identity", fill="red")+
  theme_bw() + 
  scale_color_economist()+
  theme(axis.text.x=element_text(size=rel(0.8), angle=90),plot.title = element_text(size=14,hjust = 0.5, face="bold.italic")) +
  ggtitle("Median IBU by Region") +
  labs(x="Region",y="IBU")

#  Plot a bar chart to compare Median of ABV by Region

BrewRegion %>%   na.omit() %>%
group_by(Region) %>%
summarise_each(funs(median), Median_ABV = ABV) %>% ggplot(aes(x=Region, y=sort(Median_ABV,decreasing = TRUE))) +
  geom_bar(stat="identity", fill="red")+
  theme_bw() + 
  scale_color_economist()+
  theme(axis.text.x=element_text(size=rel(0.8), angle=90),plot.title = element_text(size=14,hjust = 0.5, face="bold.italic")) +
  ggtitle("Median ABV by Region") +
  labs(x="Region",y="ABV")

#  Plot a bar chart to compare Median of IBU by Region

BrewRegion %>%   na.omit() %>%
group_by(Region) %>%
summarise_each(funs(median), Median_IBU = IBU) %>% ggplot(aes(x=Region, y=sort(Median_IBU,decreasing = TRUE))) +
  geom_bar(stat="identity", fill="red")+
  theme_bw() + 
  scale_color_economist()+
  theme(axis.text.x=element_text(size=rel(0.8), angle=90),plot.title = element_text(size=14,hjust = 0.5, face="bold.italic")) +
  ggtitle("Median IBU by Region") +
  labs(x="Region",y="IBU")

````````

### Analysis Of Variance
````````
# Compute the analysis of variance for ABV mean
BeerABV.aov <- aov(ABV ~ Region, data = BrewRegion)
# Summary of the analysis
summary(BeerABV.aov)

# There is strong evidence showing that at confidence level of 0.05 the mean of ABV in each region are different (P-Value = 0.02) 

# Compute the analysis of variance for IBU mean
BeerIBU.aov <- aov(IBU ~ Region, data = BrewRegion)
# Summary of the analysis
summary(BeerIBU.aov)

# There is strong evidence showing that at confidence level of 0.05 the mean of IBU in each region are different (P-Value < 0.0001) 

````````

## Conclusion
After using the strategic tools and concepts that will be used in application is tidying the data (merging the two datasets and making the data ready for analysis), finding the number of breweries in each state, computing the median alcohol content (ABV) and international betterness of each state (IBU), finding which state has the the maximum alcohol content and which state has the most bitter beer. The question 'Is there an apparent relationship between the bitterness of the beer and its alcoholic content?', was answered. After plotting the data using a scatterplot there was strong visual evidence of the existence of a relationship between IBU and ACV. Since the answer to the question was a 'yes', further analysis was taken. An Anova was conducted to see if there was a difference in IBU and AVC. The conclusion to that particualar test was that there was a relationship between IBU and ACV. With this conclusion a linear regression model was constructed and an equation for the model was found. After noticing that there was an apparent relationship between IBU and ACV by state, advanced analysis of the data was conducted looking at the IBU and ACV by regions. The regions in which states were categorized are: South, West, Northeast, and North Central. After catergorizing states into regions, histograms, boxplots, and barplots were used to depict the IBV and ABV by regions and the medians of the IBV and ABV were also plotted by histograms, boxplots, and barplots. Final analysis include an Analysis of Variance (ANOVA), to test the claim that ABV and IBU differ by region. To take a further look into which regions differ, the Bonferroni Multiple Comparison Procedure was used. From this procedure, it was found that ABV differs in the North Central and Northeast region. IBU differs in the West and North Central region. When comparing both IBU and ABV by region, we find that they both differ in the West region and the North Central region.  In conclusion, our interesting find from the data after such analyses is that there is an apparent relationshiop between the International Bitterness Unit (IBU) and Alcohol Content by Volume (ABV). In relation to beer and beer sales, one, because of the relationship between IBU and ABV, you can predict the ABV given an IBU. Also, when braking the relationship between IBU and ABV by region or state, we can closely look at the preference of regions to increase sales. We could even investigate ways to give a certain region or population a great beer to give a 'buzz' without a high IBU or craft a great beer with a high IBU without a high ABV. In the long run, this discovery of the relationship between IBU and ABV, can be used in a constructive way for a win-win situation in the future. 

